### ISSUE TITLE
Implement create-clarity-dev package

### ISSUE THREAD

**Issue by zone117x** [blockstack/clarity-js-sdk#19]
Implement the [`npm init`](https://docs.npmjs.com/cli/init) package allowing for something like:

1. `npm init @blockstack/clarity-dev` -- generates a ready-to-go clarity dev project (similar to yeoman), probably containing something like simple hello-world smart contract. 
2. `npm test` -- deploys contract(s), runs the ts or js contract tests. 

The `clarity-tutorials` package could be used as a generation output command -- something like: 
1. `npm init @blockstack/clarity-dev -- tutorial` -- generates the same project but includes the rocket tutorial contracts. 
2. `npm test` -- same thing (deploys and tests rocket contracts). 

Note: the `create-clarity-dev` package is named as such to work with `npm init` semantics (the `create-` prefix). 

### Tasks:

* [x] Yeoman generator package.
* [x] TypeScript dev-environment project generation.
* [ ] JavaScript dev-environment project generation.
* [x] Standalone `npm init [...]` compatible package (without `yo` dependency).
